/*
  Moves APERAK response rows that were stored in CCCSFTPXML into CCCAPERAK.

  Review mode by default: this script ends with ROLLBACK.
  After checking the SELECT results, replace ROLLBACK with COMMIT.
*/

BEGIN TRAN;

WITH source_rows AS (
  SELECT
    x.CCCSFTPXML,
    ISNULL(x.TRDR_CLIENT, 1) AS TRDR_CLIENT,
    x.TRDR_RETAILER AS SAVED_TRDR_RETAILER,
    CAST(x.XMLFILENAME AS VARCHAR(MAX)) AS APERAK_FILENAME,
    x.XMLDATE,
    CAST(x.XMLDATA.query('/DXMessage/MessageDate/text()') AS VARCHAR(20)) AS MESSAGEDATE,
    CAST(x.XMLDATA.query('/DXMessage/MessageTime/text()') AS VARCHAR(20)) AS MESSAGETIME,
    CAST(x.XMLDATA.query('/DXMessage/MessageOrigin/text()') AS VARCHAR(100)) AS MESSAGEORIGIN,
    CAST(x.XMLDATA.query('/DXMessage/DocumentReference/text()') AS VARCHAR(100)) AS RAW_DOCUMENTREFERENCE,
    CAST(x.XMLDATA.query('/DXMessage/DocumentUID/text()') AS VARCHAR(100)) AS DOCUMENTUID,
    CAST(x.XMLDATA.query('/DXMessage/SupplierReceiverCode/text()') AS VARCHAR(100)) AS SUPPLIERRECEIVERCODE,
    CAST(x.XMLDATA.query('/DXMessage/DocumentResponse/text()') AS VARCHAR(100)) AS DOCUMENTRESPONSE,
    CAST(x.XMLDATA.query('/DXMessage/DocumentDetail/text()') AS VARCHAR(MAX)) AS DOCUMENTDETAIL
  FROM CCCSFTPXML x
  WHERE CAST(x.XMLFILENAME AS VARCHAR(MAX)) LIKE 'APERAK[_]%'
     OR ISNULL(x.EDIDOCTYPE, '') = 'APERAK'
), normalized AS (
  SELECT
    s.*,
    CASE
      WHEN s.RAW_DOCUMENTREFERENCE LIKE 'INVOIC[_]%'
        THEN PARSENAME(REPLACE(s.RAW_DOCUMENTREFERENCE, '_', '.'), 3)
      WHEN s.RAW_DOCUMENTREFERENCE = 'Necunoscut'
        AND CHARINDEX('Nume fisier: INVOIC_', s.DOCUMENTDETAIL) > 0
        AND CHARINDEX('_', s.DOCUMENTDETAIL, CHARINDEX('Nume fisier: INVOIC_', s.DOCUMENTDETAIL) + LEN('Nume fisier: INVOIC_')) > 0
        THEN SUBSTRING(
          s.DOCUMENTDETAIL,
          CHARINDEX('Nume fisier: INVOIC_', s.DOCUMENTDETAIL) + LEN('Nume fisier: INVOIC_'),
          CHARINDEX('_', s.DOCUMENTDETAIL, CHARINDEX('Nume fisier: INVOIC_', s.DOCUMENTDETAIL) + LEN('Nume fisier: INVOIC_'))
            - (CHARINDEX('Nume fisier: INVOIC_', s.DOCUMENTDETAIL) + LEN('Nume fisier: INVOIC_'))
        )
      ELSE s.RAW_DOCUMENTREFERENCE
    END AS DOCUMENTREFERENCE
  FROM source_rows s
), linked AS (
  SELECT
    n.*,
    f.FINDOC,
    f.TRDR AS RESOLVED_TRDR_RETAILER,
    f.XMLFILENAME AS INVOICE_XMLFILENAME,
    f.XMLSENTDATE
  FROM normalized n
  OUTER APPLY (
    SELECT TOP 1
      a.FINDOC,
      a.TRDR,
      c.CCCXmlFile AS XMLFILENAME,
      c.CCCXMLSendDate AS XMLSENTDATE
    FROM FINDOC a
    LEFT JOIN MTRDOC c ON c.FINDOC = a.FINDOC
    WHERE a.SOSOURCE = 1351
      AND a.FPRMS = 712
      AND a.ISCANCEL = 0
      AND a.FINCODE LIKE '%' + n.DOCUMENTREFERENCE + '%'
    ORDER BY a.TRNDATE DESC, a.FINDOC DESC
  ) f
)
INSERT INTO CCCAPERAK (
  TRDR_RETAILER,
  TRDR_CLIENT,
  FINDOC,
  XMLFILENAME,
  XMLSENTDATE,
  MESSAGEDATE,
  MESSAGETIME,
  MESSAGEORIGIN,
  DOCUMENTREFERENCE,
  DOCUMENTUID,
  SUPPLIERRECEIVERCODE,
  DOCUMENTRESPONSE,
  DOCUMENTDETAIL
)
SELECT
  ISNULL(l.RESOLVED_TRDR_RETAILER, l.SAVED_TRDR_RETAILER),
  l.TRDR_CLIENT,
  ISNULL(l.FINDOC, 0),
  ISNULL(l.INVOICE_XMLFILENAME, l.APERAK_FILENAME),
  ISNULL(CONVERT(VARCHAR(30), l.XMLSENTDATE, 120), ''),
  l.MESSAGEDATE,
  l.MESSAGETIME,
  l.MESSAGEORIGIN,
  l.DOCUMENTREFERENCE,
  l.DOCUMENTUID,
  l.SUPPLIERRECEIVERCODE,
  l.DOCUMENTRESPONSE,
  l.DOCUMENTDETAIL
FROM linked l
WHERE NOT EXISTS (
  SELECT 1
  FROM CCCAPERAK a
  WHERE ISNULL(a.DOCUMENTUID, '') = ISNULL(l.DOCUMENTUID, '')
    AND ISNULL(a.DOCUMENTRESPONSE, '') = ISNULL(l.DOCUMENTRESPONSE, '')
    AND ISNULL(CAST(a.DOCUMENTDETAIL AS VARCHAR(MAX)), '') = ISNULL(l.DOCUMENTDETAIL, '')
);

SELECT @@ROWCOUNT AS inserted_into_cccaperak;

SELECT
  COUNT(*) AS remaining_aperak_in_cccsftpxml
FROM CCCSFTPXML
WHERE CAST(XMLFILENAME AS VARCHAR(MAX)) LIKE 'APERAK[_]%'
   OR ISNULL(EDIDOCTYPE, '') = 'APERAK';

/* Run this DELETE only after confirming inserted_into_cccaperak is correct. */
-- DELETE FROM CCCSFTPXML
-- WHERE CAST(XMLFILENAME AS VARCHAR(MAX)) LIKE 'APERAK[_]%'
--    OR ISNULL(EDIDOCTYPE, '') = 'APERAK';

ROLLBACK;
-- COMMIT;